version: "1.0"
info:
  model: int-scaffold
packages:
- name: STT_DemoProject
  gitServerName: STT Github
  gitUrl: https://github.com/staillansag
  gitUsername: staillansag
  gitBranch: main
services:
- serviceName: project.stt_demo.integrations:TestFlow
  packages:
  - name: STT_DemoProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
