version: "1.0"
info:
  model: int-scaffold
packages:
- name: STT_DemoProject
  gitServerName: STT Github
  gitUrl: https://github.com/staillansag
  gitUsername: staillansag
  gitBranch: main
services:
- serviceName: project.stt_demo.integrations:sayhello
  packages:
  - name: STT_DemoProject
    version: "1.0"
